#!/usr/bin/env python3
"""Analyze exported tickets and build a lightweight operations report.

The script expects the output generated by `scripts/export_tickets.py`.
By default it reads the most recent `exports/tickets-*` directory and writes:

- report.md
- summary.json
- tickets_enriched.csv
- lab_summary.csv
- category_summary.csv
- priority_summary.csv
- effort_mismatches.csv
- eta_changes.csv
- overdue_open_tickets.csv
- skill_signals.csv
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import math
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


DATE_FMT = "%Y-%m-%d"
OPEN_STATUSES = {"NEW", "TRIAGE", "IN_PROGRESS", "WAITING"}
DONE_STATUSES = {"DONE", "CLOSED"}
EFFORT_SCALE = {"S": 1, "M": 2, "L": 3, "XL": 4}
TOP_KEYWORDS_DEFAULT = 12
KEYWORD_MIN_COUNT_DEFAULT = 2
TOKEN_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9_+#./-]*")
STOPWORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "by",
    "con",
    "da",
    "dei",
    "del",
    "della",
    "delle",
    "di",
    "do",
    "done",
    "for",
    "from",
    "gli",
    "how",
    "i",
    "if",
    "il",
    "in",
    "is",
    "it",
    "la",
    "le",
    "lo",
    "needs",
    "nel",
    "nella",
    "no",
    "non",
    "of",
    "on",
    "or",
    "per",
    "please",
    "requested",
    "should",
    "sono",
    "su",
    "that",
    "the",
    "this",
    "ticket",
    "to",
    "un",
    "una",
    "with",
    "yes",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input-dir",
        help="Export directory produced by export_tickets.py. Defaults to the latest exports/tickets-* directory.",
    )
    parser.add_argument(
        "--out-dir",
        help="Directory where the analysis files will be written. Defaults to <input-dir>/analysis.",
    )
    parser.add_argument(
        "--top-keywords",
        type=int,
        default=TOP_KEYWORDS_DEFAULT,
        help=f"Top recurring keywords to keep per group (default: {TOP_KEYWORDS_DEFAULT}).",
    )
    parser.add_argument(
        "--keyword-min-count",
        type=int,
        default=KEYWORD_MIN_COUNT_DEFAULT,
        help=f"Minimum keyword frequency to include in the report (default: {KEYWORD_MIN_COUNT_DEFAULT}).",
    )
    return parser.parse_args()


def latest_export_dir(base_dir: Path) -> Path:
    candidates = [p for p in base_dir.glob("tickets-*") if p.is_dir()]
    if not candidates:
        raise FileNotFoundError("No export directories found under exports/. Run scripts/export_tickets.py first.")
    return sorted(candidates)[-1]


def parse_timestamp(value: Any) -> dt.datetime | None:
    if value in (None, "", "-"):
        return None

    if isinstance(value, dt.datetime):
        if value.tzinfo is None:
            return value.replace(tzinfo=dt.timezone.utc)
        return value.astimezone(dt.timezone.utc)

    if isinstance(value, str):
        raw = value.strip()
        if not raw:
            return None
        if raw.endswith("Z"):
            raw = raw[:-1] + "+00:00"
        try:
            parsed = dt.datetime.fromisoformat(raw)
        except ValueError:
            return None
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=dt.timezone.utc)
        return parsed.astimezone(dt.timezone.utc)

    if isinstance(value, dict) and "seconds" in value:
        try:
            seconds = float(value["seconds"])
            nanos = float(value.get("nanoseconds", 0))
        except (TypeError, ValueError):
            return None
        return dt.datetime.fromtimestamp(seconds + nanos / 1e9, tz=dt.timezone.utc)

    return None


def parse_date(value: Any) -> dt.date | None:
    if value in (None, "", "-"):
        return None

    if isinstance(value, dt.date) and not isinstance(value, dt.datetime):
        return value

    if isinstance(value, dt.datetime):
        return value.date()

    if isinstance(value, str):
        raw = value.strip()
        if not raw:
            return None
        if len(raw) >= 10:
            raw = raw[:10]
        try:
            return dt.datetime.strptime(raw, DATE_FMT).date()
        except ValueError:
            return None

    return None


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def iso_or_blank(value: dt.datetime | None) -> str:
    return value.astimezone(dt.timezone.utc).isoformat() if value else ""


def date_or_blank(value: dt.date | None) -> str:
    return value.isoformat() if value else ""


def safe_int(value: Any) -> int:
    if value in (None, ""):
        return 0
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def coalesce_text(*values: Any, default: str = "") -> str:
    for value in values:
        if isinstance(value, str):
            stripped = value.strip()
            if stripped:
                return stripped
    return default


def normalize_group(value: Any, default: str = "Unspecified") -> str:
    if isinstance(value, str):
        stripped = value.strip()
        if stripped:
            return stripped
    return default


def normalize_effort(value: Any) -> str:
    if not isinstance(value, str):
        return ""
    raw = value.strip().upper()
    return raw if raw in EFFORT_SCALE else ""


def effort_delta(requested: str, current: str) -> int | None:
    if requested not in EFFORT_SCALE or current not in EFFORT_SCALE:
        return None
    return EFFORT_SCALE[current] - EFFORT_SCALE[requested]


def median(values: list[float]) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    mid = len(ordered) // 2
    if len(ordered) % 2:
        return ordered[mid]
    return (ordered[mid - 1] + ordered[mid]) / 2


def round_or_none(value: float | None, digits: int = 1) -> float | None:
    if value is None:
        return None
    if math.isnan(value):
        return None
    return round(value, digits)


def tokenize(text: str) -> list[str]:
    tokens: list[str] = []
    for match in TOKEN_RE.finditer(text.lower()):
        token = match.group(0).strip("._-/+#")
        if len(token) < 3:
            continue
        if token in STOPWORDS:
            continue
        if token.isdigit():
            continue
        tokens.append(token)
    return tokens


def average(values: list[float]) -> float | None:
    if not values:
        return None
    return sum(values) / len(values)


def load_comments_by_ticket(path: Path | None) -> dict[str, list[dict[str, Any]]]:
    if path is None or not path.exists():
        return {}

    comments_raw = load_json(path)
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in comments_raw:
        if not isinstance(row, dict):
            continue
        ticket_id = str(row.get("ticket_id") or "").strip()
        if not ticket_id:
            continue
        grouped[ticket_id].append(row)

    for ticket_id, rows in grouped.items():
        rows.sort(key=lambda item: parse_timestamp(item.get("createdAt")) or dt.datetime.min.replace(tzinfo=dt.timezone.utc))

    return grouped


def analyze_tickets(
    tickets_raw: list[dict[str, Any]],
    comments_by_ticket: dict[str, list[dict[str, Any]]],
    *,
    top_keywords: int,
    keyword_min_count: int,
) -> dict[str, Any]:
    today = dt.datetime.now(dt.timezone.utc).date()

    enriched_rows: list[dict[str, Any]] = []
    status_counter: Counter[str] = Counter()
    current_priority_counter: Counter[str] = Counter()
    requested_priority_counter: Counter[str] = Counter()
    category_counter: Counter[str] = Counter()
    current_lab_counter: Counter[str] = Counter()
    requested_lab_counter: Counter[str] = Counter()
    lab_summary: dict[str, dict[str, Any]] = defaultdict(
        lambda: {
            "tickets_total": 0,
            "open_tickets": 0,
            "done_tickets": 0,
            "overdue_open_tickets": 0,
            "median_ticket_age_days": [],
            "eta_shift_days": [],
            "effort_delta": [],
        }
    )
    category_summary: dict[str, dict[str, Any]] = defaultdict(
        lambda: {
            "tickets_total": 0,
            "open_tickets": 0,
            "done_tickets": 0,
            "overdue_open_tickets": 0,
            "median_ticket_age_days": [],
            "eta_shift_days": [],
            "effort_delta": [],
        }
    )

    effort_mismatches: list[dict[str, Any]] = []
    eta_changes: list[dict[str, Any]] = []
    overdue_open_tickets: list[dict[str, Any]] = []

    keyword_buckets: dict[tuple[str, str], Counter[str]] = defaultdict(Counter)
    comment_counts: list[int] = []
    resolution_ages: list[float] = []

    for ticket in tickets_raw:
        if not isinstance(ticket, dict):
            continue

        ticket_id = str(ticket.get("id") or "").strip()
        if not ticket_id:
            continue

        requester = ticket.get("requesterSubmission") if isinstance(ticket.get("requesterSubmission"), dict) else {}

        status = normalize_group(ticket.get("status"), default="UNKNOWN")
        current_lab = normalize_group(ticket.get("lab"))
        requested_lab = normalize_group(requester.get("lab"))
        category = normalize_group(ticket.get("category"))
        priority = normalize_group(ticket.get("priority"))
        requested_priority = normalize_group(requester.get("priority"))
        current_eta = parse_date(ticket.get("expectedDeliveryDate"))
        requested_eta = parse_date(requester.get("expectedDeliveryDate"))
        current_effort = normalize_effort(ticket.get("effortAdmin") or ticket.get("effortGuess"))
        requested_effort = normalize_effort(requester.get("effortGuess"))
        created_at = parse_timestamp(ticket.get("createdAt"))
        updated_at = parse_timestamp(ticket.get("updatedAt"))
        is_open = status in OPEN_STATUSES
        is_done = status in DONE_STATUSES
        age_days = (today - created_at.date()).days if created_at else None
        days_to_eta = (current_eta - today).days if current_eta else None
        requested_days_to_eta = (requested_eta - today).days if requested_eta else None
        eta_shift_days = (current_eta - requested_eta).days if current_eta and requested_eta else None
        comment_rows = comments_by_ticket.get(ticket_id, [])
        comment_count = max(len(comment_rows), safe_int(ticket.get("commentCount")))
        last_comment_at = parse_timestamp(ticket.get("lastCommentAt"))
        if last_comment_at is None and comment_rows:
            last_comment_at = parse_timestamp(comment_rows[-1].get("createdAt"))

        status_counter[status] += 1
        current_priority_counter[priority] += 1
        requested_priority_counter[requested_priority] += 1
        category_counter[category] += 1
        current_lab_counter[current_lab] += 1
        requested_lab_counter[requested_lab] += 1
        comment_counts.append(comment_count)

        lab_row = lab_summary[current_lab]
        lab_row["tickets_total"] += 1
        category_row = category_summary[category]
        category_row["tickets_total"] += 1

        if is_open:
            lab_row["open_tickets"] += 1
            category_row["open_tickets"] += 1
        if is_done:
            lab_row["done_tickets"] += 1
            category_row["done_tickets"] += 1
        if age_days is not None:
            lab_row["median_ticket_age_days"].append(age_days)
            category_row["median_ticket_age_days"].append(age_days)
        if eta_shift_days is not None:
            lab_row["eta_shift_days"].append(eta_shift_days)
            category_row["eta_shift_days"].append(eta_shift_days)
        delta = effort_delta(requested_effort, current_effort)
        if delta is not None:
            lab_row["effort_delta"].append(delta)
            category_row["effort_delta"].append(delta)

        if is_open and current_eta and current_eta < today:
            overdue_days = (today - current_eta).days
            lab_row["overdue_open_tickets"] += 1
            category_row["overdue_open_tickets"] += 1
            overdue_open_tickets.append(
                {
                    "ticket_id": ticket_id,
                    "title": ticket.get("title", ""),
                    "lab": current_lab,
                    "category": category,
                    "status": status,
                    "priority": priority,
                    "eta": date_or_blank(current_eta),
                    "overdue_days": overdue_days,
                    "requester_eta": date_or_blank(requested_eta),
                    "creator_email": ticket.get("creatorEmail", ""),
                }
            )

        if is_done and created_at and updated_at and updated_at >= created_at:
            resolution_ages.append((updated_at - created_at).total_seconds() / 86400)

        if eta_shift_days not in (None, 0):
            eta_changes.append(
                {
                    "ticket_id": ticket_id,
                    "title": ticket.get("title", ""),
                    "lab": current_lab,
                    "category": category,
                    "status": status,
                    "requested_eta": date_or_blank(requested_eta),
                    "current_eta": date_or_blank(current_eta),
                    "eta_shift_days": eta_shift_days,
                    "days_to_eta": days_to_eta if days_to_eta is not None else "",
                }
            )

        if delta not in (None, 0):
            effort_mismatches.append(
                {
                    "ticket_id": ticket_id,
                    "title": ticket.get("title", ""),
                    "lab": current_lab,
                    "category": category,
                    "status": status,
                    "requested_effort": requested_effort,
                    "current_effort": current_effort,
                    "effort_delta": "" if delta is None else delta,
                }
            )

        text_blob = " ".join(
            filter(
                None,
                [
                    coalesce_text(ticket.get("title")),
                    coalesce_text(ticket.get("description")),
                    coalesce_text(ticket.get("definitionOfDone")),
                    coalesce_text(requester.get("description")),
                    coalesce_text(requester.get("definitionOfDone")),
                    category,
                ],
            )
        )
        for token in tokenize(text_blob):
            keyword_buckets[("lab", current_lab)][token] += 1
            keyword_buckets[("category", category)][token] += 1

        enriched_rows.append(
            {
                "ticket_id": ticket_id,
                "title": coalesce_text(ticket.get("title")),
                "status": status,
                "category": category,
                "lab_current": current_lab,
                "lab_requested": requested_lab,
                "priority_current": priority,
                "priority_requested": requested_priority,
                "eta_current": date_or_blank(current_eta),
                "eta_requested": date_or_blank(requested_eta),
                "eta_shift_days": "" if eta_shift_days is None else eta_shift_days,
                "days_to_eta_current": "" if days_to_eta is None else days_to_eta,
                "days_to_eta_requested": "" if requested_days_to_eta is None else requested_days_to_eta,
                "overdue_open": "yes" if is_open and current_eta and current_eta < today else "no",
                "effort_current": current_effort,
                "effort_requested": requested_effort,
                "effort_delta": "" if delta is None else delta,
                "commercially_available": coalesce_text(ticket.get("commerciallyAvailable"), default="unknown"),
                "can_be_deferred": coalesce_text(ticket.get("canBeDeferred"), default="unknown"),
                "why_not_deferred_code": coalesce_text(ticket.get("whyNotDeferredCode")),
                "creator_email": coalesce_text(ticket.get("creatorEmail")),
                "assignee_email": coalesce_text(ticket.get("assigneeEmail")),
                "created_at": iso_or_blank(created_at),
                "updated_at": iso_or_blank(updated_at),
                "ticket_age_days": "" if age_days is None else age_days,
                "comment_count": comment_count,
                "last_comment_at": iso_or_blank(last_comment_at),
            }
        )

    def finalize_group_rows(source: dict[str, dict[str, Any]], key_name: str) -> list[dict[str, Any]]:
        rows: list[dict[str, Any]] = []
        for key, values in sorted(source.items()):
            rows.append(
                {
                    key_name: key,
                    "tickets_total": values["tickets_total"],
                    "open_tickets": values["open_tickets"],
                    "done_tickets": values["done_tickets"],
                    "overdue_open_tickets": values["overdue_open_tickets"],
                    "median_ticket_age_days": round_or_none(median(values.get("median_ticket_age_days", []))),
                    "average_eta_shift_days": round_or_none(average(values.get("eta_shift_days", []))),
                    "average_effort_delta": round_or_none(average(values.get("effort_delta", []))),
                }
            )
        return rows

    lab_summary_rows = finalize_group_rows(lab_summary, "lab")
    category_summary_rows = finalize_group_rows(category_summary, "category")

    priority_summary_rows = []
    priority_keys = sorted(set(current_priority_counter) | set(requested_priority_counter))
    for key in priority_keys:
        priority_summary_rows.append(
            {
                "priority": key,
                "current_count": current_priority_counter.get(key, 0),
                "requested_count": requested_priority_counter.get(key, 0),
            }
        )

    status_summary_rows = [{"status": key, "count": count} for key, count in sorted(status_counter.items())]

    skill_signal_rows: list[dict[str, Any]] = []
    for (group_type, group_value), counter in sorted(keyword_buckets.items()):
        kept = 0
        for keyword, count in counter.most_common():
            if count < keyword_min_count:
                continue
            skill_signal_rows.append(
                {
                    "group_type": group_type,
                    "group_value": group_value,
                    "keyword": keyword,
                    "count": count,
                }
            )
            kept += 1
            if kept >= top_keywords:
                break

    priority_changes = [
        row
        for row in enriched_rows
        if row["priority_requested"] not in ("", "Unspecified")
        and row["priority_current"] not in ("", "Unspecified")
        and row["priority_requested"] != row["priority_current"]
    ]

    summary = {
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "tickets_total": len(enriched_rows),
        "open_tickets": sum(1 for row in enriched_rows if row["status"] in OPEN_STATUSES),
        "done_tickets": sum(1 for row in enriched_rows if row["status"] in DONE_STATUSES),
        "overdue_open_tickets": len(overdue_open_tickets),
        "tickets_with_requester_snapshot": sum(
            1 for ticket in tickets_raw if isinstance(ticket.get("requesterSubmission"), dict) and ticket.get("requesterSubmission")
        ),
        "tickets_with_comments": sum(1 for row in enriched_rows if safe_int(row["comment_count"]) > 0),
        "average_comment_count": round_or_none(average(comment_counts)),
        "median_comment_count": round_or_none(median([float(c) for c in comment_counts])),
        "approx_resolution_days_average": round_or_none(average(resolution_ages)),
        "approx_resolution_days_median": round_or_none(median(resolution_ages)),
        "priority_changes": len(priority_changes),
        "effort_changes": len(effort_mismatches),
        "eta_changes": len(eta_changes),
        "top_labs": current_lab_counter.most_common(5),
        "top_categories": category_counter.most_common(5),
    }

    return {
        "summary": summary,
        "status_summary_rows": status_summary_rows,
        "priority_summary_rows": priority_summary_rows,
        "lab_summary_rows": lab_summary_rows,
        "category_summary_rows": category_summary_rows,
        "effort_mismatches": sorted(effort_mismatches, key=lambda row: (row["lab"], row["category"], row["ticket_id"])),
        "eta_changes": sorted(eta_changes, key=lambda row: (row["eta_shift_days"], row["ticket_id"]), reverse=True),
        "overdue_open_tickets": sorted(
            overdue_open_tickets, key=lambda row: (row["overdue_days"], row["priority"], row["ticket_id"]), reverse=True
        ),
        "skill_signal_rows": skill_signal_rows,
        "enriched_rows": sorted(enriched_rows, key=lambda row: (row["status"], row["lab_current"], row["ticket_id"])),
    }


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    fieldnames: list[str] = []
    seen: set[str] = set()
    for row in rows:
        for key in row:
            if key not in seen:
                seen.add(key)
                fieldnames.append(key)

    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in fieldnames})


def write_json(path: Path, payload: Any) -> None:
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")


def render_table(rows: list[dict[str, Any]], columns: list[str]) -> str:
    if not rows:
        return "_No data._"

    header = "| " + " | ".join(columns) + " |"
    divider = "| " + " | ".join("---" for _ in columns) + " |"
    body = []
    for row in rows:
        values = []
        for col in columns:
            value = row.get(col, "")
            values.append("" if value is None else str(value))
        body.append("| " + " | ".join(values) + " |")
    return "\n".join([header, divider, *body])


def render_report(input_dir: Path, out_dir: Path, analysis: dict[str, Any]) -> str:
    summary = analysis["summary"]
    lines = [
        "# Ticket Analysis Report",
        "",
        f"- Source export: `{input_dir}`",
        f"- Analysis output: `{out_dir}`",
        f"- Generated at: `{summary['generated_at']}`",
        "",
        "## Overview",
        "",
        f"- Total tickets: **{summary['tickets_total']}**",
        f"- Open tickets: **{summary['open_tickets']}**",
        f"- Done/closed tickets: **{summary['done_tickets']}**",
        f"- Overdue open tickets: **{summary['overdue_open_tickets']}**",
        f"- Tickets with requester snapshot: **{summary['tickets_with_requester_snapshot']}**",
        f"- Tickets with comments: **{summary['tickets_with_comments']}**",
        f"- Average comments per ticket: **{summary['average_comment_count']}**",
        f"- Approx. median resolution days (using `updatedAt` as proxy): **{summary['approx_resolution_days_median']}**",
        "",
        "## Status",
        "",
        render_table(analysis["status_summary_rows"], ["status", "count"]),
        "",
        "## Priority",
        "",
        render_table(analysis["priority_summary_rows"], ["priority", "current_count", "requested_count"]),
        "",
        "## Labs",
        "",
        render_table(
            analysis["lab_summary_rows"],
            [
                "lab",
                "tickets_total",
                "open_tickets",
                "done_tickets",
                "overdue_open_tickets",
                "median_ticket_age_days",
                "average_eta_shift_days",
                "average_effort_delta",
            ],
        ),
        "",
        "## Categories",
        "",
        render_table(
            analysis["category_summary_rows"],
            [
                "category",
                "tickets_total",
                "open_tickets",
                "done_tickets",
                "overdue_open_tickets",
                "median_ticket_age_days",
                "average_eta_shift_days",
                "average_effort_delta",
            ],
        ),
        "",
        "## Overdue Open Tickets",
        "",
        render_table(
            analysis["overdue_open_tickets"][:15],
            ["ticket_id", "lab", "category", "priority", "status", "eta", "overdue_days", "title"],
        ),
        "",
        "## ETA Changes",
        "",
        render_table(
            analysis["eta_changes"][:15],
            ["ticket_id", "lab", "status", "requested_eta", "current_eta", "eta_shift_days", "title"],
        ),
        "",
        "## Effort Changes",
        "",
        render_table(
            analysis["effort_mismatches"][:15],
            ["ticket_id", "lab", "status", "requested_effort", "current_effort", "effort_delta", "title"],
        ),
        "",
        "## Skill Signals",
        "",
        "Recurring keywords are a proxy only: they can help spot repeated capability requests, but they are not a direct skill taxonomy.",
        "",
        render_table(analysis["skill_signal_rows"][:30], ["group_type", "group_value", "keyword", "count"]),
        "",
        "## Notes",
        "",
        "- `average_eta_shift_days` is current ETA minus requester ETA. Positive means the plan moved later.",
        "- `average_effort_delta` is admin/current effort minus requester effort using `S < M < L < XL`.",
        "- Resolution timing is approximate because the dataset does not store a dedicated close timestamp yet.",
        "- For older tickets, requester snapshots may be missing if they were created before the snapshot field was introduced.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    args = parse_args()

    input_dir = Path(args.input_dir) if args.input_dir else latest_export_dir(Path("exports"))
    tickets_path = input_dir / "tickets.json"
    comments_path = input_dir / "comments.json"
    if not tickets_path.exists():
        raise FileNotFoundError(f"Missing tickets export: {tickets_path}")

    out_dir = Path(args.out_dir) if args.out_dir else input_dir / "analysis"
    out_dir.mkdir(parents=True, exist_ok=True)

    tickets_raw = load_json(tickets_path)
    if not isinstance(tickets_raw, list):
        raise RuntimeError(f"Unexpected tickets format in {tickets_path}")

    comments_by_ticket = load_comments_by_ticket(comments_path if comments_path.exists() else None)

    analysis = analyze_tickets(
        tickets_raw,
        comments_by_ticket,
        top_keywords=max(1, args.top_keywords),
        keyword_min_count=max(1, args.keyword_min_count),
    )

    write_json(out_dir / "summary.json", analysis["summary"])
    write_csv(out_dir / "tickets_enriched.csv", analysis["enriched_rows"])
    write_csv(out_dir / "status_summary.csv", analysis["status_summary_rows"])
    write_csv(out_dir / "priority_summary.csv", analysis["priority_summary_rows"])
    write_csv(out_dir / "lab_summary.csv", analysis["lab_summary_rows"])
    write_csv(out_dir / "category_summary.csv", analysis["category_summary_rows"])
    write_csv(out_dir / "effort_mismatches.csv", analysis["effort_mismatches"])
    write_csv(out_dir / "eta_changes.csv", analysis["eta_changes"])
    write_csv(out_dir / "overdue_open_tickets.csv", analysis["overdue_open_tickets"])
    write_csv(out_dir / "skill_signals.csv", analysis["skill_signal_rows"])
    (out_dir / "report.md").write_text(render_report(input_dir, out_dir, analysis), encoding="utf-8")

    print(
        json.dumps(
            {
                "input_dir": str(input_dir),
                "out_dir": str(out_dir),
                **analysis["summary"],
            },
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ModuleNotFoundError as exc:
        missing = exc.name or "unknown"
        raise SystemExit(
            "Missing Python dependency "
            f"'{missing}'. Install the script requirements first with:\n"
            f"  {sys.executable} -m pip install -r scripts/requirements.txt"
        ) from exc
